export interface PricingItem {
  costume: string
  washAndFold: string
  washAndIroning: string
  steamPress: string
  dryClean: string
  stitching: string
}

export const serviceItemsData: PricingItem[] = [
  {
    costume: "Shirt",
    washAndFold: "₹50",
    washAndIroning: "₹65",
    steamPress: "₹80",
    dryClean: "₹100",
    stitching: "Per damaged portion",
  },
  {
    costume: "T-shirt",
    washAndFold: "₹55",
    washAndIroning: "₹60",
    steamPress: "₹100",
    dryClean: "-",
    stitching: "Per damaged portion",
  },
  {
    costume: "Pants",
    washAndFold: "₹50",
    washAndIroning: "₹75",
    steamPress: "₹40",
    dryClean: "₹120",
    stitching: "Per damaged portion",
  },
  {
    costume: "Jeans",
    washAndFold: "₹90",
    washAndIroning: "₹95",
    steamPress: "₹95",
    dryClean: "₹145",
    stitching: "Per damaged portion",
  },
  {
    costume: "Churidar Set - Normal",
    washAndFold: "₹80*",
    washAndIroning: "₹100",
    steamPress: "₹90*",
    dryClean: "₹250*",
    stitching: "Per damaged portion",
  },
  {
    costume: "Churidar Set - Party Wear",
    washAndFold: "₹100*",
    washAndIroning: "₹120",
    steamPress: "₹170",
    dryClean: "₹400*",
    stitching: "Per damaged portion",
  },
  {
    costume: "Saree Normal",
    washAndFold: "₹50",
    washAndIroning: "Saree type matter",
    steamPress: "₹90*",
    dryClean: "₹150*",
    stitching: "Per damaged portion",
  },
  {
    costume: "Saree Party Wear",
    washAndFold: "₹100*",
    washAndIroning: "₹150",
    steamPress: "NA",
    dryClean: "₹200*",
    stitching: "Per damaged portion",
  },
  {
    costume: "Tops",
    washAndFold: "₹60",
    washAndIroning: "₹55",
    steamPress: "₹70",
    dryClean: "₹100*",
    stitching: "Per damaged portion",
  },
  {
    costume: "Lehanka",
    washAndFold: "As per cloth",
    washAndIroning: "As per cloth",
    steamPress: "As per cloth",
    dryClean: "₹100*",
    stitching: "Per damaged portion",
  },
  {
    costume: "Blazer",
    washAndFold: "₹100",
    washAndIroning: "₹120",
    steamPress: "NA",
    dryClean: "₹250",
    stitching: "Per damaged portion",
  },
  {
    costume: "Kurtha",
    washAndFold: "₹65",
    washAndIroning: "₹80",
    steamPress: "₹90",
    dryClean: "₹110*",
    stitching: "Per damaged portion",
  },
  {
    costume: "Leggins",
    washAndFold: "₹70",
    washAndIroning: "₹75",
    steamPress: "₹80",
    dryClean: "₹110*",
    stitching: "Per damaged portion",
  },
  {
    costume: "Set Mund",
    washAndFold: "₹100",
    washAndIroning: "₹150",
    steamPress: "₹160",
    dryClean: "₹140*",
    stitching: "Per damaged portion",
  },
  {
    costume: "Pillow Cover",
    washAndFold: "₹20",
    washAndIroning: "₹25",
    steamPress: "₹40",
    dryClean: "₹700*",
    stitching: "Per damaged portion",
  },
  {
    costume: "Bath Towel",
    washAndFold: "₹70",
    washAndIroning: "₹80",
    steamPress: "NA",
    dryClean: "₹100*",
    stitching: "Per damaged portion",
  },
  {
    costume: "Bed Sheet (S / D / H)",
    washAndFold: "₹60 / ₹70 / ₹80",
    washAndIroning: "₹80 / ₹90 / ₹100",
    steamPress: "₹80 / ₹90 / ₹110",
    dryClean: "₹100 / ₹120 / ₹150*",
    stitching: "Per damaged portion",
  },
  {
    costume: "Blanket (S / D / H)",
    washAndFold: "₹80",
    washAndIroning: "₹100",
    steamPress: "NA",
    dryClean: "₹180 / ₹250 / ₹350*",
    stitching: "Per damaged portion",
  },
  {
    costume: "Quilt (S / D / H)",
    washAndFold: "NA",
    washAndIroning: "NA",
    steamPress: "NA",
    dryClean: "₹220 / ₹300 / ₹400*",
    stitching: "Per damaged portion",
  },
  {
    costume: "Socks",
    washAndFold: "NA",
    washAndIroning: "₹30",
    steamPress: "NA",
    dryClean: "NA",
    stitching: "Per damaged portion",
  },
  {
    costume: "Blazer",
    washAndFold: "₹100",
    washAndIroning: "₹120",
    steamPress: "NA",
    dryClean: "₹250",
    stitching: "Per damaged portion",
  },
  {
    costume: "Curtain (S / M / H)",
    washAndFold: "As per size",
    washAndIroning: "NA",
    steamPress: "As per size",
    dryClean: "As per size",
    stitching: "Per damaged portion",
  },
  {
    costume: "Dhothi",
    washAndFold: "₹70",
    washAndIroning: "₹60",
    steamPress: "₹70",
    dryClean: "₹100*",
    stitching: "Per damaged portion",
  },
  {
    costume: "Gown",
    washAndFold: "As per cloth",
    washAndIroning: "As per cloth",
    steamPress: "As per cloth",
    dryClean: "₹100*",
    stitching: "Per damaged portion",
  },
  {
    costume: "Inners",
    washAndFold: "",
    washAndIroning: "₹20",
    steamPress: "",
    dryClean: "",
    stitching: "",
  },
  {
    costume: "Under Garments",
    washAndFold: "",
    washAndIroning: "₹20",
    steamPress: "",
    dryClean: "",
    stitching: "Per damaged portion",
  },
]
